### ISSUE TITLE
[Enhancement] Allow the crosshair to work with henkelmax/camera-utils

### ISSUE THREAD

**Issue by Y4k3d0** [Crendgrim/DynamicCrosshair#101]
Currently, there's a convenient option which allows the crosshair behavior to be consistent in third person view. When coupled with Camera Utils's [custom perspectives](https://github.com/henkelmax/camera-utils?tab=readme-ov-file#customizable-third-person-perspectives), I think it could be a nice addition to make them more playable.

**Comment by Crendgrim** [comment]
Related: Crendgrim/DynamicCrosshairCompat#10

Sadly, this appears to still hold true. You could try to voice your support in henkelmax/camera-utils#56 which has not been closed as a duplicate of henkelmax/camera-utils#10 yet.
