### ISSUE TITLE
1.21 NeoForge Crash (ConfigHandler)

### ISSUE THREAD

**Issue by GreatKingKeenan** [Crendgrim/DynamicCrosshair#103]
https://mclo.gs/hSyAzuQ

**Comment by Crendgrim** [comment]
I cannot replicate. Under which conditions does it crash?

**Comment by Crendgrim** [comment]
That must be a compatibility issue. On a fresh instance with latest NeoForge & DC it does not crash. Try removing mods until it stops crashing to figure out which other mod causes this.

**Comment by GreatKingKeenan** [comment]
Yeah. I figured. A lot of mods have compatibility issues in 1.21. It's not a big deal though since from the look of it, most devs are working on 1.21.1. Just thought I'd post my crash log still.

**Comment by DFreezerR** [comment]
In my case the issue was this mod [Remove Reloading Screen](https://modrinth.com/mod/rrls)

> Caused by: java.lang.NullPointerException: Cannot invoke "mod.crend.dynamiccrosshair.config.ConfigHandler.getCrosshairStyleRegular()" because "mod.crend.dynamiccrosshair.DynamicCrosshairMod.config" is null

this was the same error message I had
DC - `dynamiccrosshair-8.1+1.21-neoforge`
NF - `21.0.167`
RRLS - `rrls-5.0.7+mc1.21-forge`
JAVA -  `jdk-21.0.4.7-hotspot`

**Comment by FreshImmuc** [comment]
+1, sadly i am not able to remove one of the mods, @DFreezerR mentioned, since they are mandatory for the modpack

**Comment by Crendgrim** [comment]
Relevant: Crendgrim/AutoHUD#133

This is an incompatibility with the library mod "placebo" which, for some reasons I even after talking to its author do not understand, decides to silently change the order in which mods are initialised. The crash will be fixed in the upcoming version of DC.

**Comment by FreshImmuc** [comment]
> Relevant: [Crendgrim/AutoHUD#133](https://github.com/Crendgrim/AutoHUD/issues/133)
> 
> This is an incompatibility with the library mod "placebo" which, for some reasons I even after talking to its author do not understand, decides to silently change the order in which mods are initialised. The crash will be fixed in the upcoming version of DC.

Thank you, I'm excited to use this mod! :)
