### ISSUE TITLE
Compatibility with Flour's Various Tweaks

### ISSUE THREAD

**Issue by ardissaps** [Crendgrim/DynamicCrosshair#11]
Crashlog :
https://pastebin.com/yVfZwVPb

Launcher Log : 
https://paste.atlauncher.com/view/fee7f4fb-fec0-48f3-8b6f-bbaf3ab270bd

**Comment by Crendgrim** [comment]
I pushed version 2.0.1 which doesn't crash, but has the limitation was described above. I will leave this issue open to track compatibility with FVT.

**Comment by ardissaps** [comment]
> I pushed version 2.0.1 which doesn't crash, but has the limitation as described above. I will leave this issue open to track compatibility with FVT.

Is it possible to make it also work on modded equipment?

**Comment by Crendgrim** [comment]
With my infrastructure work going into 2.0, that is indeed possible. Please feel free to open a new issue for the mods you'd like to see supported. Though I can't promise that I'll work on them immediately.

**Comment by Crendgrim** [comment]
I have added the colour settings to my mod in 2.1. Will have to double check priorities to make sure it applies correctly after FVT is updated to fail-soft on mixing in.

**Comment by Flourick** [comment]
> I have added the colour settings to my mod in 2.1. Will have to double check priorities to make sure it applies correctly after FVT is updated to fail-soft on mixing in.

I'll test it properly when I release the 1.19 version.

**Comment by Crendgrim** [comment]
It is possible that I will have to change my mixin's priority. I can do that without issue if it makes compatibility easier.

**Comment by Flourick** [comment]
> It is possible that I will have to change my mixin's priority. I can do that without issue if it makes compatibility easier.

Yeah, you should have it > 1000 so that it get's applied instead of mine. Just put it at 1001 and it will work.

**Comment by Crendgrim** [comment]
Will do that with the next release :)

**Comment by Crendgrim** [comment]
Done for 1.19, and works well.
