### ISSUE TITLE
There is a display error in the attack progress indicator after modifying the texture pack.

### ISSUE THREAD

**Issue by Fogg05** [Crendgrim/DynamicCrosshair#111]
**There is a display error in the attack progress indicator after modifying the texture pack.**
![Image_25171421431073](https://github.com/user-attachments/assets/eb061cb3-0868-4c60-a7af-6982c5d3ea0d)
This involves crosshair_attack_indicator_full.png and crosshair_attack_indicator_progress.png, which are displayed when the crosshair is pointed at attackable entities. I created this texture pack with a high-definition style. I need to modify these two images to the black-and-white opaque style shown in the picture to ensure the anti-aliasing parts of the image display correctly. Normally, the white parts would automatically change color according to the original crosshair's functionality, the black parts would be transparent, and the gray parts would become semi-transparent to achieve proper anti-aliasing display. However, recent updates to the mod have broken this vanilla feature. Now, using black-and-white opaque images results in the same error. Although my method might seem peculiar, it is the only way to achieve anti-aliasing. I believe this should be understood as the mod not being fully compatible with all vanilla features, essentially a bug. I have received many player feedback reports about this issue recently and hope it can be fixed. Thanks.

**Comment by Fogg05** [comment]
![QQ20241201-193242](https://github.com/user-attachments/assets/0915d0a3-8fcd-49b9-b6dc-7882bf757141)

> understood

ecognized

**Comment by Crendgrim** [comment]
Ah, that is bad. What version of Minecraft / mod loader is this?

**Comment by Fogg05** [comment]
My Resource Pack👇. You can download it in the Release.
https://github.com/Fogg05/CozyUI-Plus
My users said the bug occurs in v9.0 of your mod and can be fixed by downgrading back to v8.1.
![Screenshot_2024-12-02-11-32-37-317_com tencent mo](https://github.com/user-attachments/assets/69081bc0-3a6e-4d1d-b8ad-9f9351a09d8c)
![Screenshot_2024-12-02-11-32-10-932_com tencent mo](https://github.com/user-attachments/assets/1eeca1e7-3b9a-495d-84fb-e105e8ee13dc)

**Comment by Crendgrim** [comment]
- Which Minecraft version does this happen on?
- Which mod loader does this happen on?
- Is AutoHUD in the instance as well?

**Comment by Crendgrim** [comment]
I believe to have fixed it in DynamicCrosshair 9.3. Feel free to reopen if I missed some version / mod loader combination somehow.

**Comment by Fogg05** [comment]
It looks like a similar bug has occurred again.

![Image](https://github.com/user-attachments/assets/c77cd15b-f7d8-4180-81fa-7c728677569a)
<img width="1440" height="1920" alt="Image" src="https://github.com/user-attachments/assets/3603b0db-2c57-4164-8500-04269c800dd7" />
![Image](https://github.com/user-attachments/assets/c0dd739e-eca0-469e-bbe6-2404f28aa10d)
![Image](https://github.com/user-attachments/assets/2b73dcff-b8c1-4d3a-98fa-8695fa1ac7ba)
![Image](https://github.com/user-attachments/assets/c888315a-071b-4171-a3da-fa5af3a31daf)

- 1.20.1
- Fabric
- Dynamic Crosshair 9.8
- with Dynamic Crosshair Compat 4.3

A popular Mod Pack recently released by a Chinese author has installed your mod. Many players have encountered this bug during actual gameplay. I'm currently trying to get in touch with the Mod Pack author as well. Hopefully, it can be fixed soon. 🧐

- Mod Pack
https://www.bilibili.com/video/BV1VXtqzSECX/
https://pan.quark.cn/s/eaea50184e65#/list/share/407c620c59bf400c9a48476808543063
