### ISSUE TITLE
Custom crosshair when a bow/crossbow is fully charged

### ISSUE THREAD

**Issue by vos6434** [Crendgrim/DynamicCrosshair#12]
Bows/crossbows should have the diagonal cross when fully charged letting the user know they are ready to fire.

Holding the bow
![2022-06-08_03 40 38](https://user-images.githubusercontent.com/21976486/172519723-6002af40-0588-4f4d-86e4-60033f7a52b1.png)

Fully charged bow
![2022-06-08_03 41 17](https://user-images.githubusercontent.com/21976486/172519763-4ab1218e-d3b7-42a3-b420-a84e9305583c.png)

**Comment by Crendgrim** [comment]
Good idea! Implemented in version 2.2.
