### ISSUE TITLE
1.19 crash on 3.0 

### ISSUE THREAD

**Issue by Kidihh** [Crendgrim/DynamicCrosshair#19]
The mod was working fine until the last update (3.0) on minecraft 1.19

Crashlog: https://pastebin.com/8gAig6TW

**Comment by Crendgrim** [comment]
I cannot reproduce this crash. Can you tell me what you have in your hand / what block you are looking at when you're crashing?

**Comment by Crendgrim** [comment]
Thank you! That makes sense now. I pushed a fix.
