### ISSUE TITLE
3.1 [1.18.1] Crash with Minecart In Hand

### ISSUE THREAD

**Issue by DreamsieWasTaken** [Crendgrim/DynamicCrosshair#22]
Game crashes when hovering over a block while there is a minecart in your selected slot. Was able to reproduce it consistently. None of the installed mods tampered with minecarts.

**Comment by Crendgrim** [comment]
Interesting, this is a difference between 1.18.1 and 1.18.2 that I was not aware of. Fixed in 3.1.1.
