### ISSUE TITLE
mythic mounts incompatibility

### ISSUE THREAD

**Issue by slovinsqui** [Crendgrim/DynamicCrosshair#23]
crashes when looking at a colytra from mythic mounts mod

[crash-2022-07-09_22.17.00-client.txt](https://github.com/Crendgrim/DynamicCrosshair/files/9078501/crash-2022-07-09_22.17.00-client.txt)
d

**Comment by Crendgrim** [comment]
Ah, MythicMounts has updated to 1.19 and still has that bug. Will port the workaround from 1.18 in the next version.

**Comment by Crendgrim** [comment]
Done so in 3.3.1
