### ISSUE TITLE
Crosshair stops updating after dimension change when "Hide the crosshair whenever a screen is open" is disabled

### ISSUE THREAD

**Issue by TsukiTheDwagon** [Crendgrim/DynamicCrosshair#25]
Whenever this config option is disabled, going through a nether/end portal or swapping servers on a multiplayer network breaks the crosshair's ability to update.

From what it looks like, this seems to only break any contextual functionality related to the held item (e.g. drawing back a ranged weapon, holding a tool, etc.)

Steps to replicate:
Put a tool in your hotbar.
Step through a portal to initiate a dimension change.
Notice how the tool you're holding no longer updates the crosshair properly.

**Comment by Crendgrim** [comment]
Thank you for the report! This game keeps surprising me with how things are implemented in edge cases :)

It is fixed in 3.4
