### ISSUE TITLE
bug: ranged discharge lingers

### ISSUE THREAD

**Issue by exincore** [Crendgrim/DynamicCrosshair#26]
## What

Ranged weapons do not clear the "fully charged" state from the crosshair once fired.
Crossbow does not have a crosshair at all until fully charged.

[Screencast from 08-05-2022 02:16:13 PM.webm](https://user-images.githubusercontent.com/44628275/183147741-917652f2-aa94-4f60-a937-6ad092cca2f1.webm)

## Reproduction
Occurs on:
- Quilt Loader 0.17.1
- Fabric Loader 0.14.8

1. Install a fresh instance of Minecraft 1.19 with modloader of choice, Dynamic Crosshair 3.4 + dependencies
3. Use a ranged weapon

**Comment by Crendgrim** [comment]
Thank you for the report! Both issues are fixed in 3.5 :)
