### ISSUE TITLE
Crash with macaw doors

### ISSUE THREAD

**Issue by masmasmas66** [Crendgrim/DynamicCrosshair#27]
[crash-2022-08-15_22.03.54-client.txt](https://github.com/Crendgrim/DynamicCrosshair/files/9347805/crash-2022-08-15_22.03.54-client.txt)

**Comment by Crendgrim** [comment]
Macaw's Doors removed the garage remote item in the new version 1.0.7. Thanks for the report, will push a fix soon.

**Comment by Crendgrim** [comment]
I believe this should be fixed with DynamicCrosshairCompat 1.3
