### ISSUE TITLE
Custom Crosshair Compatibility

### ISSUE THREAD

**Issue by Tuyaudaeration** [Crendgrim/DynamicCrosshair#28]
hello, is Custom Crosshair Mod compatible with your mod? and if not, can you make it compatible in the add-on please.

**Comment by Crendgrim** [comment]
It is not, but you can create a resource pack with the crosshair styles you would like (overwriting `textures/gui/crosshairs.png`). Also you can set the colour for all of the crosshairs in this mod's settings. That only allows pixel crosshairs, however.

Sadly, Custom Crosshair Mod is closed source, so adding explicit compatibility is more complicated and not something I am very interested in maintaining. It may happen one day, but not right now.
