### ISSUE TITLE
Russian translation not working

### ISSUE THREAD

**Issue by SyberiaKey** [Crendgrim/DynamicCrosshair#3]
Maybe you forgot to set up TranslatableText?

**Comment by Crendgrim** [comment]
That is odd. All translatable text gets generated by AutoConfig, which uses TranslatableText, and all English text is taken from the translation file. So it should work just fine... but I can see that it doesn't.

**Comment by Crendgrim** [comment]
Ah, I probably found it: in `ru_ru.json`, line 30 is not terminated with a comma. That makes it malformed json, and that's likely why it doesn't get loaded. I will push an update to fix that tomorrow.

**Comment by Crendgrim** [comment]
Yep, that was it. New version pushed :)
