### ISSUE TITLE
Two sideways "L" below the crosshair at all times

### ISSUE THREAD

**Issue by FredDoesStuff** [Crendgrim/DynamicCrosshair#30]
For whatever reason, there are always two sideways Ls below the crosshair at all times, even if the crosshair changes.
![image](https://user-images.githubusercontent.com/112592014/197420170-f17538f5-c953-4e23-b245-efb7e073c1c2.png) (holding nothing and looking at nothing)
![image](https://user-images.githubusercontent.com/112592014/197420208-4f2ce7b0-871a-42d3-b579-003eb6d302df.png) (holding a sword and looking at water)

**Comment by Crendgrim** [comment]
That is the default "shield" crosshair, do you have a shield in your offhand? You can cconfigure/disable it using the "when holding shield" section of the config.

**Comment by FredDoesStuff** [comment]
This fixed my issue. Thanks!
