### ISSUE TITLE
Option to add individual items to categories

### ISSUE THREAD

**Issue by heldheld** [Crendgrim/DynamicCrosshair#32]
Say for example you play on a server that uses Fire Charges that you can shoot (making them more like fireballs). These are not recognized by DynamicCrosshair as ranged weapons and will therefore not follow rules you set up for that category, making it so there's not really an option to have the crosshair show while holding a Fire Charge without sacrificing other dynamic options. That makes it difficult to aim and shoot properly. If I could somehow add the Fire Charge (or any other item) to the ranged weapons category (or any other category), it would solve it and also open up a whole new level of customization. Or maybe add support to edit the behaviour of the cross hair when holding specific items? Not sure if that is a better solution.

**Comment by Crendgrim** [comment]
I have added support for this in DynamicCrosshair 4.1. You can now specify any number of item names for the different item categories.

There is a conceptual problem here, though: if you have a near-vanilla installation and play on several servers, these may have different such behaviour tweaks. Introducing a whole "config profile" per world/server seems overly complicated, so I opted for this solution: these new settings live on a new "Tweaks" page (with potentially more tweaks being added in the future), and there is a simple "enable tweaks" button. This way, you can e.g. configure fire charges to be considered throwable items on your server, and then simply uncheck that checkbox when you play singleplayer or on a different server. I hope that works with your use-case. :)

**Comment by heldheld** [comment]
Amazing, it seems to work perfectly!

Would it be too much to ask if you could add this to the 1.18.2 version?... That's specifically the version I need for the server that has the fire charge -> fire ball change. :)

**Comment by Crendgrim** [comment]
Apologies for the delay, I have backported it into the 1.18 version and just published 3.6+1.18.2 :)

I did not thoroughly test it, so let me know if things go burning down.

**Comment by heldheld** [comment]
Seems to work just as perfect as the 1.19 one. Thanks a lot, I think this is a great addition to your mod 😄!
