### ISSUE TITLE
Crash when connecting to certain servers

### ISSUE THREAD

**Issue by heldheld** [Crendgrim/DynamicCrosshair#33]
Whenever I have DynamicCrosshair running and join certain servers (For example MCC Island, McManhunt, TubNet) crashes the game, either right away or after a few seconds. If I remove DynamicCrosshair it works fine.

**Comment by Crendgrim** [comment]
Interesting. Can you send me a crash log of when that happens?

**Comment by heldheld** [comment]
[crash-2022-12-22_19.48.17-client.txt](https://github.com/Crendgrim/DynamicCrosshair/files/10289608/crash-2022-12-22_19.48.17-client.txt)

There you go!
This is from when I connected to MCC Island server, 3 seconds later it crashes

**Comment by Crendgrim** [comment]
I see you have OptiFabric installed. Could you test for me whether it still happens without that?

**Comment by heldheld** [comment]
I'm not sure why, but I tried it again with exactly the same setup (so including OptiFabric) and now it works fine... It's strange that it crashed consistently on certain servers before and now it just doesn't. Anyway, if the problem returns and I can narrow it down to DynamicCrosshair I'll be back, until then we can consider this issue solved!

**Comment by heldheld** [comment]
Confirmed, it was a different mod called 'More Culling' that caused the initial issues.
