### ISSUE TITLE
Option to fix this bug that makes your crosshair not centered

### ISSUE THREAD

**Issue by realFusionFusion** [Crendgrim/DynamicCrosshair#39]
https://bugs.mojang.com/browse/MC-157252

**Comment by Crendgrim** [comment]
I finally had a look at this. Will be included in the upcoming release for 1.20.2 or 1.20.3.

**Comment by eliasjurkeit** [comment]
Is it also in the release for 1.20.1 / 9.3?

**Comment by Crendgrim** [comment]
Yes, but it is fairly unstable. Subpixel positioning is awkward at best.
