### ISSUE TITLE
Add support to Arcanus

### ISSUE THREAD

**Issue by TheButterbrotMan** [Crendgrim/DynamicCrosshair#4]
Could you add compat to Arcanus please?

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/94

**Comment by Crendgrim** [comment]
Somewhat worked around in 1.2 by showing a crosshair whenever a modded item is being held.
Full mod compatibility is a huge task that I'm not willing to undergo right now, but might be in the mod's future. For now I focus on vanilla compatibility.

**Comment by TheButterbrotMan** [comment]
Could you please add a fabric tag to 1.2?

**Comment by Crendgrim** [comment]
Ah, silly Curseforge. Done.

**Comment by TheButterbrotMan** [comment]
Thank you! :)
