### ISSUE TITLE
Background of the Inventory/ containers flickers

### ISSUE THREAD

**Issue by DeadbushCarrot** [Crendgrim/DynamicCrosshair#41]
So the background of the inventory and probably other stuff like chests and the brewing stand have a weird flicker it kinda looks like a camera is being pointed at a crt tv and is reduced when v sync is on. Am still trying to test all my mods and came back with out it but am still searching
EDIT FALSE ALARM IT WAS EXORDIUM but use this as example
The option in exordium was Enabled gui set it to off to fix the issue

**Comment by Crendgrim** [comment]
Thank you, I will mention this on the mod pages!

**Comment by Crendgrim** [comment]
For future reference: https://github.com/tr7zw/Exordium/issues/58
