### ISSUE TITLE
Show the crosshair when holding item don't work with the vanilla style

### ISSUE THREAD

**Issue by Guerdi** [Crendgrim/DynamicCrosshair#42]
The title is quite explicit, the crosshair ignores the parameters involving holding certain items in hand when the "Use dynamic crosshair style" option is off.
The mod works normally on parameters involving looking at blocks or entities

**Minecraft** : `1.19`
**Quilt Loader** : `0.17.4`
**Dynamic Crosshair** : `5.3.1`

**Comment by Crendgrim** [comment]
This was an early design decision that, in retrospect, does seem wrong.

I have published version 5.4 that should change this behaviour. And very rarely have I implemented a feature by simply removing some old code :)
