### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'dynamiccorsshair'!

### ISSUE THREAD

**Issue by Kaden-Skinner** [Crendgrim/DynamicCrosshair#46]
https://paste.gg/p/anonymous/ea45614832a946bcbc804346cab10442

The launcher has updated. With that update, they made accessibility settings more accessible. This means that the first screen you see isn't the main menu. I don't know if this is related, but may help.

**Comment by Crendgrim** [comment]
This is neither urgent nor a bug.

Install cloth-config (required dependency for 5.3.1), or update DynamicCrosshsair to 5.4 (been out for a week).
