### ISSUE TITLE
6.0+ cause Quilt Loader to crash

### ISSUE THREAD

**Issue by AlfmanOO7** [Crendgrim/DynamicCrosshair#48]
[Crash Report](https://mclo.gs/HnihOdm)
[Log](https://mclo.gs/Dk5Eutg)
^for version 6.2 

Affected versions:
- 6.0
- 6.1
- 6.2

**Comment by Bellabong** [comment]
Exact same error on Fabric, but specifically the most recent version (5.6). The version before that (5.5) has a different start up error that I assumed was the reason for the same day upload and 5.4 has no issues.

**Comment by Crendgrim** [comment]
Hm, I am unable to replicate this on either Quilt or Fabric launcher.
The error message doesn't tell me anything either.

Where exactly does this error happen, on startup?

**Comment by AlfmanOO7** [comment]
Yes, the game doesn’t even launch, I have also let quilt know as the quilt launcher pops up and gives me an ‘invalid session’ error

**Comment by Crendgrim** [comment]
Weirdly, the error message points to the "take huge screenshot" method, which shouldn't have any relation to my mod at all, especially not during startup. If this is somehow caused by my mod, I must have messed things up something fierce..

**Comment by Crendgrim** [comment]
Ah, I managed to replicate it. The crash happens when both DynamicCrosshair and Memory Leak Fix are in the load order.

**Comment by Crendgrim** [comment]
I pushed versions 5.6.1 (1.19.2) and 6.2.1 (1.19.4). Can you test whether that fixes all crashes? My limited testing seemed to suggest so, but there may be new crashes now with other mods.

**Comment by AlfmanOO7** [comment]
All fixed! :D game loads fine, thank you!
