### ISSUE TITLE
Option for default crosshair don't show custom crosshairs from resource packs

### ISSUE THREAD

**Issue by realFusionFusion** [Crendgrim/DynamicCrosshair#49]

**Comment by Crendgrim** [comment]
True, "default" currently is "default style", not "default texture". You can somewhat circumvent it by adding a resource pack that replaces this mod's texture atlas: https://github.com/Crendgrim/DynamicCrosshair/blob/1.19.4/common/src/main/resources/assets/dynamiccrosshair/textures/gui/crosshairs.png

**Comment by skibidibada** [comment]
> True, "default" currently is "default style", not "default texture". You can somewhat circumvent it by adding a resource pack that replaces this mod's texture atlas: https://github.com/Crendgrim/DynamicCrosshair/blob/1.19.4/common/src/main/resources/assets/dynamiccrosshair/textures/gui/crosshairs.png

a suggestion i would add to this is connect the png files of the crosshairs to a config and make the different crosshairs able to be drawn/changed inside the game

**Comment by Crendgrim** [comment]
This has been fixed with DynamicCrosshair 7.4 for Minecraft 1.20.2 (though not 1.20 / 1.20.1).
