### ISSUE TITLE
1.20 Game Crashes at the Start

### ISSUE THREAD

**Issue by hunterdavidson** [Crendgrim/DynamicCrosshair#52]
I am using the 1.20 (7.0.1) version on fabric and it seems to not be able to start

I have checked to see if the config file was the issue as per the previous post, but I do not even have one.

[https://pastebin.com/QZWe0H6C](url)

**Comment by Crendgrim** [comment]
Ah, now it crashes if *no* config file exists. Well, that's awkward.

**Comment by Crendgrim** [comment]
Pushed version 7.0.2 to address this, will do the same for my other mods. Thanks for letting me know.
