### ISSUE TITLE
[BUG] [QUILT 1.20.1] Compatibility issue with Better Third Person and Shoulder Surfing mod

### ISSUE THREAD

**Issue by XanDorkiest** [Crendgrim/DynamicCrosshair#54]
When using Shoulder Surfing mod and Better Third Person with Dynamic Crosshair, walking around causes an offset in portions of the GUI when Dynamic Crosshair is also installed. Walking with a bow fixes this, somehow.

To reproduce: 
1. Install Shoulder Surfing, Dynamic Crosshair, and Better Third Person together.
2. Dynamic crosshair range 100 in shoulder surfing config.
3. Go on a world and walk around in third person. parts of the GUI will be moving along with the crosshair. For some reason holding a bow will fix the GUI glitch, but not holding it causes the bug to reappear.

![Screenshot 2023-06-22 202916](https://github.com/Crendgrim/DynamicCrosshair/assets/69460830/fa657bb8-f614-4de0-a314-ff9e6ba5a9e5)

4. Remove Dynamic Crosshair from the modlist and try again. The GUI will be fine.

![image](https://github.com/Crendgrim/DynamicCrosshair/assets/69460830/69c77676-5d28-49cb-b37d-78d53b7c88f3)

**Comment by Aabaddon** [comment]
i second this, the 3 mods complement each other perfectly, sadly they are not compatible

**Comment by Crendgrim** [comment]
I cannot reproduce this in Minecraft 1.20.2 with the latest versions of all these mods, so I think it's been fixed!
