### ISSUE TITLE
Crash in 1.18.2 when breaking Arundo from TerraFirmaCraft

### ISSUE THREAD

**Issue by MikeTheBuddy** [Crendgrim/DynamicCrosshair#56]
A specific crash occurs when breaking Arundo from TFC, in which the user is unable to enter the world until the mod is removed, resulting in repeated crashes.

For reference, the crash report looks like this:
[message.txt](https://github.com/Crendgrim/DynamicCrosshair/files/11995923/message.txt)

**Comment by Crendgrim** [comment]
TFC apparently changes vanilla behaviour for one of their items (presumable Arundo, whatever that is). Considering how big of a mod it is I'd wager to say that DyamicCrosshair won't work very well anyway.

**Comment by MikeTheBuddy** [comment]
It actually worked fairly well with most of the stuff within the mod, with the main thing being this plant that grows upward like sugarcane.

**Comment by Crendgrim** [comment]
Apologies for the delay. It took me a bit to reproduce because it doesn't always happen when breaking Arundo. And then I couldn't figure out exactly why it's crashing. I now pushed a version that just eats the exception so the crash doesn't happen.
