### ISSUE TITLE
Certain Crosshairs not saving color in config after game has been restarted/opened anew.

### ISSUE THREAD

**Issue by Zaromen1** [Crendgrim/DynamicCrosshair#57]
Looking at interactable block, Holding usable item, Holding shield, Holding correct tool and Holding incorrect tool:
These crosshair types do not seem to save themselves in the config or reset automatically after the game has been restarted / opened anew.
All other crosshair trigger do have their correct color saved and seem to continue to keep them after a restart, only the above mentioned reset after restart.

**Comment by Crendgrim** [comment]
Oh, I accidentally'd a single line causing this. Thank you for the report! Fixed in 7.0.4
