### ISSUE TITLE
Plz compatible with 1.16.5

### ISSUE THREAD

**Issue by Oururis** [Crendgrim/DynamicCrosshair#58]
Can you make a version compatible with 1.16.5? if it can,Thank you! I can see the crosshair through the background when using a transparent GUI, and it's annoying. I want to hide the crosshair when any menu is open. Your mod looks perfect for this, but it's not compatible with 1.16.5. I tried to find a similar mod, but couldn't find one.

**Comment by Crendgrim** [comment]
No sorry, I have no interest in working on ancient versions of Minecraft. If someone wants to port it and makes a pull request, that is very welcome, but I won't port it myself.
