### ISSUE TITLE
dynamic crosshair 7.0.4/7.0.3 is not 1.20.1 in modrinth

### ISSUE THREAD

**Issue by lostopkk** [Crendgrim/DynamicCrosshair#60]
![image](https://github.com/Crendgrim/DynamicCrosshair/assets/50776714/c1d3c7c7-3361-4c4d-af2a-93f3d2298533)

**Comment by Crendgrim** [comment]
Oh how stupid. Thank you! Fixed on Modrinth and CurseForge.
