### ISSUE TITLE
Immersive Portals blank out crosshair

### ISSUE THREAD

**Issue by f0rttnite** [Crendgrim/DynamicCrosshair#61]
Looking through portals from Immersive Portals seems to register to the crosshair as looking at air, and the crosshair doesn't change based on what you're looking at through the portal

**Comment by Crendgrim** [comment]
Oh, that is an intriguing compatibility challenge.

**Comment by Crendgrim** [comment]
I finally got around to finishing this. There is now full support for Immersive Portals, with everything working perfectly fine across dimension boundaries! :D
