### ISSUE TITLE
[v.7.1] Tag 1.20.1 is missing on Modrinth

### ISSUE THREAD

**Issue by IntM4rco** [Crendgrim/DynamicCrosshair#65]
I don't know if you did it by accident or for a reason.
<img width="1239" alt="Screenshot 2023-08-31 alle 16 45 12" src="https://github.com/Crendgrim/DynamicCrosshair/assets/124934175/edcdfb3c-f443-4e14-86c4-3307973120d5">

**Comment by Crendgrim** [comment]
🤦 I forgot to update the list again, sorry.

**Comment by IntM4rco** [comment]
Ah ok, I closed the issue because I thought there was a reason you didn't tag for 1.20.1
