### ISSUE TITLE
Dynamically hide option still hides the crosshair when holding nothing, even when set to disable

### ISSUE THREAD

**Issue by skibidibada** [Crendgrim/DynamicCrosshair#66]
![image](https://github.com/Crendgrim/DynamicCrosshair/assets/111621104/7a3a154d-d3e9-4958-b249-9066032dd13e)
![2023-09-09_14 34 01](https://github.com/Crendgrim/DynamicCrosshair/assets/111621104/be299747-3886-4e6e-a706-ef9f263aba44)

**Comment by Crendgrim** [comment]
There is a minor bug when the crosshair was hidden, and then you set it to "disabled", it won't show up until looking at a block or entity again. But after that, it reliably stays visible for me.

**Comment by Crendgrim** [comment]
That is an interesting bug. Which version of Minecraft are you using, which modloader, and what other mods?

**Comment by skibidibada** [comment]
> That is an interesting bug. Which version of Minecraft are you using, which modloader, and what other mods?

1.20.1, prism launcher

**Comment by Crendgrim** [comment]
modloader would be Fabric, Quilt, Forge, or NeoForge

**Comment by skibidibada** [comment]
> modloader would be Fabric, Quilt, Forge, or NeoForge

ah sorry, quilt

**Comment by Crendgrim** [comment]
I cannot reproduce this with only DynamicCrosshair, Quilted Fabric API, YACL, and ModMenu. Could you try to figure out which mod causes this? Are there any other mods in your instance that tweak the crosshair or HUD in general?

**Comment by Crendgrim** [comment]
Ohh, I think I understand the problem. You're holding a shield and have disabled the shield crosshair; is that correct?

**Comment by Crendgrim** [comment]
I can reproduce this issue if "Behavior / Holding shield" is active, but "Style / Holding shield / Crosshair Style" is set to "Disabled". While I need to handle this combination better, can you try setting "Behavior / Holding shield" to false and see if it fixes your issue?

**Comment by Crendgrim** [comment]
Under the assumption that this is the case (as it is the only way I was able to reproduce the issue), I just pushed version 7.5 for 1.20.2 that should "fix" this by preventing the shield (or any modifier) style to be set to "Disabled", and have everything configurable only through the Behavior tab instead. If this does in fact not fix your issue, feel free to re-open!
