### ISSUE TITLE
[Suggestion] List of interactable blocks in config for crosshair modifier 

### ISSUE THREAD

**Issue by CatAndPaste** [Crendgrim/DynamicCrosshair#69]
For better compatibility with other mods. I do really love the brackets while hovering over vanilla blocks with GUIs. Would love to have a list of additionalInteractableBlocks in config file :3

I'm playing on Forge, so Dynamic Crosshairs Compat is not available for me, unfortunately.

**Comment by Crendgrim** [comment]
This seems so obvious in retrospect, I wonder why I never implemented it. Good idea.

**Comment by Crendgrim** [comment]
Decided to simply backport it to every version since 1.19.2. Published all of those. Thank you for the suggestion!
