### ISSUE TITLE
Shield crosshair is bugged!

### ISSUE THREAD

**Issue by Harsh-bot-beep** [Crendgrim/DynamicCrosshair#70]
Look at this you will know.
Its the crosshair of shield there is smol line in top left and down right lines are thinned out.
![Screenshot 2023-10-27 120804](https://github.com/Crendgrim/DynamicCrosshair/assets/76815433/398d191c-4529-4b57-b99d-9b740f3badd7)

**Comment by Harsh-bot-beep** [comment]
happens on latest version btw.

**Comment by Crendgrim** [comment]
I could replicate similar, but not the same, visual glitches because of that centered crosshair setting. "Fixed" this issue by making that opt-in (defaults to false) instead; the perfectly centered crosshair will then just work on specific scale / resolution combinations.
