### ISSUE TITLE
[1.20.1] Startup issue (crash) on Forge 1.20.1 with YetAnotherConfigLib installed

### ISSUE THREAD

**Issue by ReeCodes** [Crendgrim/DynamicCrosshair#71]
Crash log: https://mclo.gs/6MKYDLP

Latest log: https://mclo.gs/7072Kko

**Comment by Crendgrim** [comment]
YACL (yet-another-config-lib) 3.2 for Forge 1.20.1 is broken. YACL 3.0 for Forge 1.20.1 does not support the features I'm using. It's a very frustrating situation. See also https://github.com/isXander/YetAnotherConfigLib/issues/116

If you uninstall YACL, DynamicCrosshair should work (except that you won't have a graphical configuration screen). Though you may run into other issues if other mods have a hard dependency on YACL.

**Comment by Crendgrim** [comment]
Updated upstream bug report, but no fix yet: isXander/YetAnotherConfigLib#124

**Comment by AsgerJon** [comment]
This issue appears on Fabric as well

**Comment by Crendgrim** [comment]
No, that must be a different problem. Could you create a new issue with your logs included?

**Comment by AsgerJon** [comment]
> No, that must be a different problem. Could you create a new issue with your logs included?

I will show a minimal example when I get home in a few hours.

**Comment by Crendgrim** [comment]
YACL *finally* updated to fix this. Update YACL and everything should work again.
