### ISSUE TITLE
Incompatibility with Let's Do Vinery

### ISSUE THREAD

**Issue by CatAndPaste** [Crendgrim/DynamicCrosshair#73]
Installing both Dynamic Crosshair and Let's Do Vinery mod results in very weird Stem (pole used to grow Vinery grapes) behaviour: https://www.youtube.com/watch?v=00AeLJAeVXI

What is in the video: stems being placed without button click and are broken (1 instead of 2 blocks height). There are a lot of mods being installed when video was recorded, but I tested it only with Architectury, Do Api, Vinery and Dynamic Crosshair with NeoForge 47.1.79 and can confirm that this issue is still out there.

Issue in Let's Do's official Discord: https://discord.com/channels/1078796799185277079/1175957958945951774/1175957958945951774

Love both of your mods so much T.T Cheers <3~

**Comment by Crendgrim** [comment]
On a cursory glance of the vinery mod's code, this seems like the potential problem:
https://github.com/satisfyu/Vinery/blob/baa4d1ecda0112b416390ae027817083311fc28f/common/src/main/java/satisfyu/vinery/block/stem/PaleStemBlock.java#L57

I'm checking whether a block is placeable in the "currently targeted block" context, and this appears to be related to that. And it places an item from the player's hand in the block above the targeted block. That seems consistent with the behaviour in your video.

**Comment by Crendgrim** [comment]
The vinery authors said they would change this on their end.

@CatAndPaste how strongly do you feel about this issue? I can add a temporary hack until it is fixed if you want.

**Comment by Crendgrim** [comment]
Update: has been fixed upstream (unreleased). I will close this issue once the new version of Vinery gets published.

**Comment by Crendgrim** [comment]
Vinery update has been released
