### ISSUE TITLE
Latest version incompatible with autohud

### ISSUE THREAD

**Issue by FrosteByte** [Crendgrim/DynamicCrosshair#75]
Game runs fine on quilt loader 22.0 with either autohud 6.3.2 or dynamic crosshair 7.4.2, but not both together.
Crash report: [crash-2023-12-29_15.16.41-client.txt](https://github.com/Crendgrim/DynamicCrosshair/files/13796491/crash-2023-12-29_15.16.41-client.txt)

Edit - I am currently using the following with no issues:
autohud-6.3.2+1.20.1-fabric
dynamiccrosshair-7.4.1+1.20-fabric
dynamiccrosshair-compat-3.7.1+1.20.1

**Comment by Crendgrim** [comment]
I cannot replicate this crash with:

Minecraft 1.20.1
Quilt-Loader 0.22.0
autohud 6.3.2
dynamiccrosshair 7.4.2
dynamiccrosshaircompat 3.7.1
modmenu 7.2.2
quilted-fabric-api 7.4.0+0.90.0
yacl 3.2.1

Which, as far as I can tell, is the same versions as you have. And I don't think any other mods should interfere with it. Very odd.
Could you share your config files for both autohud and dynamiccrosshair? I have no idea why it wouldn't find the class that's clearly in the archive, though...

**Comment by FrosteByte** [comment]
I still got a crash with the exact same and only the mods listed above. Here's that report, maybe a little cleaner than the other one.
[crash-2023-12-29_21.50.11-client.txt](https://github.com/Crendgrim/DynamicCrosshair/files/13797191/crash-2023-12-29_21.50.11-client.txt)

Apparently json5 isn't supported, so here's the configs: [configs.zip](https://github.com/Crendgrim/DynamicCrosshair/files/13797184/configs.zip)

**Comment by Crendgrim** [comment]
Still cannot reproduce this at all. Works perfectly fine. Very odd. What launcher do you use?

**Comment by Crendgrim** [comment]
https://modrinth.com/mod/autohud/versions?g=1.20.1&l=fabric

Oh. I figured it out. I forgot to increase the version number, so there's *two* versions 6.3.2 ... oops

**Comment by Crendgrim** [comment]
Re-released the fake 6.3.2 as 6.3.3. I am surprised both Modrinth and CurseForge just silently accepted a duplicate version number. Thank you for the report, I'll add that to my "double-and-triple check list".

**Comment by FrosteByte** [comment]
I noticed the same version number but I guess I thought it was just the same file haha - glad to help!
