### ISSUE TITLE
[Enhancement] Option to highlight the crosshair based on whether the item is cooling down

### ISSUE THREAD

**Issue by LoliColleen** [Crendgrim/DynamicCrosshair#76]
Currently, this mod allows that the crosshair can be highlighted when the player is holding specfic items. But some items (such as shield, ender pearls) have a cooling down duration. So I hope that the highlighting on the crosshair may be disabled when the item is cooling down.

**Comment by Crendgrim** [comment]
That should already be a thing for usable items + throwables (like ender pearls). The crosshair shouldn't trigger during cooldowns. Does that not work for you? If so, what mod loader + versions of MC & the mod are you on?

**Comment by LoliColleen** [comment]
It works for the Interactable items, but is doesnt work for the shield entry. Although it works if I add shield to the Interactable items, but I just want to divide the sheild and the other items.

**Comment by LoliColleen** [comment]
Whenever a living entity with axe attack the player raising shield

**Comment by Crendgrim** [comment]
Apologies for the delay, I totally thought I had already published this! Pushed version 7.7 to mod stores that fixes this. Thank you for letting me know!

If you need it backported to any version before 1.20.4 let me know, and I'll publish the relevant version as well.
