### ISSUE TITLE
[Enhancement] allow using every style for every option

### ISSUE THREAD

**Issue by iambeingtracked** [Crendgrim/DynamicCrosshair#81]
There are 2 groups of styles: first has Default, Cross, Diamond, and Caret
second has: Brackets, BracketsBottom, BracketsTop, RoundBrackets, Lines, LineBottom, Dot, DiagonalCross

The enhancement is to make using any of those styles anywhere possible. For example, to set Looking at entity to Brackets

**Comment by Crendgrim** [comment]
I've wanted to do this for a while, but it's not as easy as it seems. Because modifiers are designed to be shown alongside any of the main crosshair styles, things get ugly when combining either two main styles or two modifiers.

This is still on my wish list, but it would require a substantial rework of the whole mod to cleanly implement.

**Comment by iambeingtracked** [comment]
Isn't there some handling to that? Like a priority or something? Because you can hold a shield and some food at the same time and what happens to me is that it shows the crosshair for the usable item, when switching to an another item it shows the crosshair for the shield.

**Comment by Crendgrim** [comment]
The priority is currently intrinsic by order of checks. Whichever conditions first match is the crosshair that is shown. This is done once for the main crosshair and once for the modifier. The order in which checks are done is then arranged in a way that matches vanilla's behaviour. By doing it this way, I can short-circuit expensive calculations by checking all trivial cases first. But it does become a problem for this request, and this is why a substantial rewrite would be needed.

**Comment by Crendgrim** [comment]
Implemented with the rewrite (including an in-game painter for custom styles!) in DynamicCrosshair 8.0 for 1.21.
