### ISSUE TITLE
Crosshair not fully invisible Auto HUD

### ISSUE THREAD

**Issue by Alixxx-please** [Crendgrim/DynamicCrosshair#82]
![2024-04-10_22 37 40](https://github.com/Crendgrim/DynamicCrosshair/assets/121387740/6a940d91-28ff-45c2-9bc5-08cfa55515d0)
After a few tests I concluded that both mods made the crosshair **almost** invisible, more like transparent. Adding the compat mod doesn't change anything. A fix would be appreciated, thanks a lot! :)

**Comment by Crendgrim** [comment]
This is on purpose, it is controlled with the setting `advanced.crosshair.maximumFade` in AutoHUD:
![image](https://github.com/Crendgrim/DynamicCrosshair/assets/3526017/e44600f3-0e69-4937-bb3d-2a7a5f726384)

Set this to 0 to make it fully disappear.
