### ISSUE TITLE
make "holding block/weapon/toom" a modifier because offhand 

### ISSUE THREAD

**Issue by tuopi27** [Crendgrim/DynamicCrosshair#83]
there is instances that you can be holding a block in the offhand and a tool in the main, so i would want a way to show both the block and the mainhand crosshairs. (this would assume u also do the suggestion to allow any style on any crosshair)

**Comment by Crendgrim** [comment]
Kind of implemented by the rewrite. In the default configuration, this should always display off-hand crosshairs if they can act in the current context. You can finetune it somewhat using the coalesce settings.
