### ISSUE TITLE
[BUG] crash when opening options screen

### ISSUE THREAD

**Issue by Reycko** [Crendgrim/DynamicCrosshair#85]
Version 1.20.1

java.lang.IncompatibleClassChangeError: class dev.isxander.yacl3.gui.OptionListWidget overrides final method 

Full crash log:
https://mclo.gs/1L7K7Di

This also happens when the only mods loaded are YACL and Dynamic Crosshair

**Comment by Crendgrim** [comment]
Bug is in YACL: isXander/YetAnotherConfigLib#182

**Comment by NovaViper** [comment]
Oddly I got a different error from OP, mine's saying `[10:01:11] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown! net.minecraft.ReportedException: mouseClicked event handler`. Doesn't mention YACL at all 🤔 

My instance's running Minecraft 1.21.1 with NeoForge v21.1.34
Log: https://mclo.gs/t9Pf8SU
