### ISSUE TITLE
Version of dynamiccrosshair-api is "${api_version}"

### ISSUE THREAD

**Issue by JetbladeDevsStuff** [Crendgrim/DynamicCrosshair#87]
It looks like you forgot to add a processResources block in in the build.grade for api-fabric. Making a PR soon.

**Comment by Crendgrim** [comment]
Of course something like this would happen, thanks for the report!

Did that cause issues anywhere?

**Comment by JetbladeDevsStuff** [comment]
Not that I saw, but Fabric issued a warning saying that it cannot parse the version.

**Comment by JetbladeDevsStuff** [comment]
Finally figured this out. BTW, this was hard to test due to the 1.21 version of AutoHUD not being published (new branch not pushed?).
