### ISSUE TITLE
"regular" crosshair always stays as cross-open, even when changed

### ISSUE THREAD

**Issue by tuopi27** [Crendgrim/DynamicCrosshair#91]
seen here: cross-open crosshair when i had set it to dot. this happens even if **every single style** is set to something other than cross-open
![2024-07-24_16 36 35](https://github.com/user-attachments/assets/e8dee58a-a1e7-4681-ab43-f54572f94407)
![2024-07-24_16 37 11](https://github.com/user-attachments/assets/7d308a81-441f-4e88-b726-444385013f4e)

interestingly, the regular crosshair _does_ show up when holding an unloaded crossbow or uncharged trident/bow
![2024-07-24_16 42 42](https://github.com/user-attachments/assets/b48ab72c-b2d9-4fbf-ad8f-b8e50ba5bc86)

**Comment by Crendgrim** [comment]
Fixed in 8.1, thank you for the report!
