### ISSUE TITLE
"always" option on "ranged weapon" doesnt work

### ISSUE THREAD

**Issue by tuopi27** [Crendgrim/DynamicCrosshair#92]
see here: "regular" crosshair style (dot) despite having ranged weapon option set to "always"
![2024-07-24_16 42 42](https://github.com/user-attachments/assets/43469810-be4f-4ed4-9b7a-36aa91c89e85)
![2024-07-24_16 46 33](https://github.com/user-attachments/assets/a8756a8d-43fa-4466-b8af-6b34f547940a)

_also happens on "ifinteractable" when uncharged or unloaded despite having arrows in inventory. not sure if that one is intentional tho_

**Comment by Crendgrim** [comment]
Which modloader & version is this on?

**Comment by tuopi27** [comment]
fabric 0.15.11

**Comment by tuopi27** [comment]
this is possibly connected to #91 given that this bug is the only exception to that bug

**Comment by Crendgrim** [comment]
I was more concerned about the Minecraft version. I'm assuming latest DC for 1.21?

**Comment by tuopi27** [comment]
oh yeah 1.21. i figured youd know that from the screenshot sorry

**Comment by Crendgrim** [comment]
Fixed in 8.1, thank you for the report!

> also happens on "ifinteractable" when uncharged or unloaded despite having arrows in inventory. not sure if that one is intentional tho
Yes, "IfInteractable" (as the UI tooltip says) shows the configured crosshair whenever the weapon is ready to be fired. So, fully drawn bow/trident, or charged crossbow.
