### ISSUE TITLE
if a single item has multiple categories, only one crosshair will show

### ISSUE THREAD

**Issue by tuopi27** [Crendgrim/DynamicCrosshair#93]
see here: trident i have set to both "throwable" and "melee weapon" shows only "throwable" crosshair even if coalesce is active for both
![2024-07-24_16 50 59](https://github.com/user-attachments/assets/b821f620-0ecd-469e-ada1-db2a40e96edf)
![2024-07-24_16 50 50](https://github.com/user-attachments/assets/a871e5d0-d5a4-4e92-a8bd-706d84992dad)

note it still coalesces with crosshairs from other sources (looking at block and looking at entity shown here)
![2024-07-24_16 53 23](https://github.com/user-attachments/assets/cad602b2-f166-4816-bccc-c31c072272f3)
![2024-07-24_16 54 07](https://github.com/user-attachments/assets/9c5e6303-f472-4e59-b943-501d353850e8)

**Comment by Crendgrim** [comment]
This is an interesting one. I will have a look at it, but I'm not sure if this is doable without massive complexity.

I do also think, though, that tridents by default should be both melee & ranged weapons.

**Comment by tuopi27** [comment]
i did throwable because ranged just.... didnt work
-even if coalesce is on, the ranged crosshair refuses to coalesce
-adding an item to the ranged weapon category just doesnt do anything
-added an item that already has a category to a second category (e.g. crossbows to usable items) again only shows one
-#92

**Comment by Crendgrim** [comment]
Okay, there were multiple bugs present here.

- The "additional ranged weapons" did not work. This should be fixed in 8.1.
- The trident is now (as of 8.1) considered both a melee and ranged weapon.
- Adding items to multiple categories does not work. This is *not* fixed in 8.1, I consider it an enhancement that I still have to think about whether I want to support it.

**Comment by Crendgrim** [comment]
I have decided that I don't want to support adding items to multiple categories in the config. Any missing behaviour like the trident I would consider a bug; and if a server drastically changes item behaviour from vanilla, then it would most likely require a small compatibility mod instead anyway.
