### ISSUE TITLE
Allow item/block blacklist for crosshair changes

### ISSUE THREAD

**Issue by egirlcatnip** [Crendgrim/DynamicCrosshair#96]
Currently, there exists a feature to add on to the whitelist of certain categories, it would be helpful if it were possible to exclude certain items or blocks from affecting the crosshair.

Torches in the offhand are a good example of a situation where someone may wish to hide the block-place crosshair.

Also the exclussion of the axe from weapons/overwriting it as a tool (not just when targetting a wood-related block) could be nice.

**Comment by Crendgrim** [comment]
This is adding a lot of complexity. I will think about it.

**Comment by Crendgrim** [comment]
I have added an option in 8.1 to disable all block crosshairs from the offhand. For now this seems like a decent compromise.

**Comment by Crendgrim** [comment]
I have decided that a combined black- and whitelist is too complicated to maintain. Specific behaviour (like axe being both melee weapon + tool, or the offhand) can be disabled already; other such cases I can add config entries for too.
