### ISSUE TITLE
[ENCHANCEMENT] Fade animation

### ISSUE THREAD

**Issue by TQCnoARosto** [Crendgrim/DynamicCrosshair#99]
Would be nice to have a fade out animation for the crosshair after x second the player is not pointing at any block. The instant show/hide is so weird.

**Comment by Crendgrim** [comment]
You can use my other mod AutoHUD for that. You can disable all of its other features if you don't want those, but keep the crosshair fade. There is inbuilt compatibility between that and DynamicCrosshair.
